services:
  # Proxy para el frontend
  frontend-proxy:
    image: nginx:alpine
    container_name: frontend-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/templates
      - ./nginx/ssl:/etc/nginx/ssl/${NGINX_SSL}/
    depends_on:
      - frontend-ui
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend-network

  frontend-ui:
    build:
      context: ./dspace-ui
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - frontend-network

volumes:
  frontend-logs:

networks:
  frontend-network:
    driver: bridge
    name: dspace-frontend-only